swagger: "2.0"
info:
  title: "Sample API"
  description: "A simple API for demonstration purposes"
  version: "1.0.0"

paths:
  /hello:
    get:
      summary: "Get Hello Message"
      description: "Returns a hello message"
      responses:
        200:
          description: "Successful response"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Hello, Swagger!"

  /echo:
    post summary: "Echo Message"
      description: "Echoes the provided message"
      parameters:
        - in: body
          name: message
          description: "Message to be echoed"
          required: true
          schema:
            type: object
            properties:
              message:
                type: string
      responses:
        200:
          description: "Successful response"
          schema:
            type: object
            properties:
              echoedMessage:
                type: string
