openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Get a list of pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              example:
                - id: 1
                  name: "Dog"
                - id: 2
                  name: "Cat"
    post:
      summary: Add a new pet
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "Bird"
      responses:
        '201':
          description: Pet added successfully
  /pets/{petId}:
    get:
      summary: Get details of a specific pet
      parameters:
        - name: petId
          in: path
          required: true
          description: ID of the pet
          schema:
            type: integer
      responses:
        '200':
          description: Details of the pet
          content:
            application/json:
              example:
                id: 1
                name: "Dog"
    put:
      summary: Update details of a specific pet
      parameters:
        - name: petId
          in: path
          required: true
          description: ID of the pet
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            exam
