name: Swagger Validation

on: [ push ]

jobs:
  test_swagger_editor_validator_service:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Service
    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - name: Get YAML files
        id: getfiles
        uses: actions/checkout@v2
        run: |
          echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
          find . -type f -iname "*.yaml" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
          FILES="$(find . -type f -iname "*.yaml")"
          echo "::set-output name=file_list::$FILES"

      - name: yaml-validator
        uses: mbowman100/yaml-validator-action@master
        if: env.FILE_COUNT != '0'
        with:
          files: ${{ env.FILE_LIST }}
