name: Swagger Validation

on: [ push ]

jobs:
  test_swagger_editor_validator_service:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Service
    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080



    steps:
      - uses: actions/checkout@v2
      - name: Get Changed Files
        id: get_changed
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA)
          
          CHANGED_FILES_WITH_EXTENSIONS=$(echo "$CHANGED_FILES" | xargs -I {} basename {})
          
          echo "::set-output name=changed_files::$CHANGED_FILES_WITH_EXTENSIONS"
      - name: Display Changed Files
        run: |
          CHANGED_FILES_WITH_EXTENSIONS="${{ steps.get_changed.outputs.changed_files_with_extensions }}"
          echo "Changed files with extensions: $CHANGED_FILES_WITH_EXTENSIONS"
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ steps.get_changed.outputs.changed_files_with_extensions }}